config/routes.rb
VinsolApp::Application.routes.draw do

  resources :users, :except => [:destroy, :edit, :update] do
    member do
      get :following, :followers
    end
  end
    
  resources :microposts, only: [:create] do
    post :retweet, :on => :member
  end
  
  resources :relationships, only: [:create, :destroy] do
    get :total_followers, :on => :collection
  end
       
  root :to => 'users#new'

end

app/models/micropost.rb
class Micropost < ActiveRecord::Base
  
  attr_accessible :content, :retweet
  belongs_to :user
  validates :content, presence:true, length: {maximum: 140}
  validates :user_id, presence: true

  default_scope order('created_at DESC')

end

app/models/relationship.rb
class Relationship < ActiveRecord::Base
  attr_accessible :followed_id
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
  
  validates :follower_id, presence: true
  validates :followed_id, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base

  attr_accessible :name
  
  has_many :microposts, dependent: :destroy
  
  has_many :relationships, foreign_key: "follower_id",
                           dependent: :destroy
  has_many :followed_users, through: :relationships,
                            source: :followed

  has_many :reverse_relationships, foreign_key: "followed_id",
                                   class_name: "Relationship",
                                   dependent: :destroy
                                 
  has_many :followers, through: :reverse_relationships, source: :follower

  before_save :downcase_name

  validates :name, presence: true, length: {maximum: 50}, uniqueness: true

  def feed
    Micropost.where("user_id in (?)" , followed_users + [self]).includes(:user)
  end

  def following?(other_user)
    relationships.find_by_followed_id(other_user.id)
  end

  def follow!(other_user)
    relationships.create!(followed_id: other_user.id)
  end

  def unfollow!(other_user)
    relationships.find_by_followed_id(other_user.id).destroy
  end

  private

  def downcase_name
    name.downcase!
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  protect_from_forgery

  include ApplicationHelper
  
  before_filter :find_current_user
  
  def find_current_user
    unless current_user
      redirect_to new_user_path
    end
  end
      
end

app/controllers/microposts_controller.rb
class MicropostsController < ApplicationController

  def create
    @micropost = current_user.microposts.build(params[:micropost])
    if @micropost.save
      flash[:success] = "Micropost created!"
      redirect_to root_path
    else
      @user = current_user
      @feed_items = @user.feed.paginate(page: params[:page])
      render 'users/show'
    end
  end

  def retweet
   @post = Micropost.find(params[:id])
   current_user.microposts.create(:content => @post.content, :retweet => true)
   @micropost = current_user.microposts.build
   @user = current_user
   @feed_items = @user.feed.paginate(page: params[:page])
   render 'users/show'
  end
  
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController

  def create
    @user = User.find(params[:relationship][:followed_id])
    current_user.follow!(@user)
    respond_to do |format|
      format.html {redirect_to @user}
      format.js do
        render :partial => 'users/unfollow'
      end
    end
  end

  def destroy
    @user = Relationship.find(params[:id]).followed
    current_user.unfollow!(@user)
    respond_to do |format|
      format.html {redirect_to @user}
      format.js { render :partial => 'users/follow' }
    end
  end

 def total_followers
   render :json => {:followers => current_user.followed_users.count }
 end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  require 'will_paginate/array'

  skip_before_filter :find_current_user, :only => [:new, :create]
  before_filter :user_present?, :only => [:new]
  before_filter :find_user, :only => [:following, :followers, :show]

  def following
    @title = "Following"
    @users = @user.followed_users.paginate(page: params[:page])
    render 'show_follow'
  end
  
  def followers
    @title = "Follower"
    @users = @user.followers.paginate(page: params[:page])
    render 'show_follow'
  end

  def show
    @micropost = current_user.microposts.build
    @feed_items = @user.feed.paginate(page: params[:page])
  end
  
  def new
    @user = User.new
  end
  
  def create
    @user = User.find_or_create_by_name(params[:user])
    if @user
      session[:user_id] = @user
      flash[:success] = "Welcome to the Vinsol App!"
      redirect_to @user
    else
      render 'new'
    end
  end
  
  def index
    @users = User.paginate(page: params[:page])
  end

  private

  def user_present?
    current_user = User.find_by_id(session[:user_id])
    if current_user.present?
      redirect_to current_user
    end
  end

  def find_user
    @user = User.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  
  def full_title(page_title)
    base_title = "Vinsol App"
    if page_title.empty?
      base_title
    else
      "#{base_title} | #{page_title}"
    end
  end

  def current_user
    @current_user ||= User.find_by_id(session[:user_id])
  end

  def current_user?(user)
    current_user == user
  end

end

app/helpers/microposts_helper.rb
module MicropostsHelper
  def wrap(content)
    sanitize(raw(content.split.map{ |s| wrap_long_string(s) }.join(' ')))
  end

  private

  def wrap_long_string(text, max_width = 30)
    zero_width_space = "&#8203;"
    regex = /.{1,#{max_width}}/
    (text.length < max_width) ? text :
      text.scan(regex).join(zero_width_space)
  end
end

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">
      <nav>
        <ul class="nav pull-right">
          <li><%= link_to "Home", root_path %></li>
            <li><%= link_to "Users", users_path %></li>
        </ul>
      </nav>
    </div>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag "application", media: "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class = "container">
      <% flash.each do|key,value| %>
        <%= content_tag(:div, value, class: "alert alert-#{key}") %>
      <% end %>
      <%= yield %>
    </div>
    </body>
  </html>

app/views/microposts/_micropost.html.erb
<% if(micropost.retweet == false || (micropost.retweet == true && !current_user?(micropost.user))) %>
<li>
  <span class="content"><%= wrap(micropost.content) %></span>
  <span class="timestamp">
      Posted <%= time_ago_in_words(micropost.created_at) %> ago
      by <%= micropost.user.name %>
  </span>
  <span>
    <% if micropost.user != current_user %>
      <%= link_to("Retweet", retweet_micropost_path(micropost), :confirm => 'Retweet this to your followers?', :method => "post") %>
    <% end %>
  </span>
</li>
<%end%>

app/views/shared/_error_messages.html.erb
<%  if object.errors.any? %>
<div id="error_explanation">
  <div class="alert alert-error">
    The form contains <%= pluralize(object.errors.count, "error") %>
   </div>
  <ul>
  <% object.errors.full_messages.each do |msg| %>
    <li>* <%= msg %></li>
    <% end %>
  </ul>
</div>
<% end %>

app/views/shared/_micropost_form.html.erb
<%= form_for(@micropost) do |f|%>
  <%=  render 'shared/error_messages', object: f.object %>
  <div id="content_text"></div>
  <div class="field">
    <%= f.text_area :content, placeholder: "Tweet..." %>
  </div>
<%=  f.submit "Tweet", class: "btn btn-large btn-primary" %>
<% end %>

app/views/shared/_stats.html.erb
<% @user ||= current_user %>
<div class="stats">
  <a href="<%= following_user_path(@user) %>">
    <strong id="following" class="stat">
      <%= @user.followed_users.count %>
    </strong>
    following
  </a>
  <a href="<%= followers_user_path(@user) %>">
    <strong id="followers" class="stat">
      <%= @user.followers.count %>
    </strong>
    followers
  </a>
</div>

app/views/shared/_user_info.html.erb
<h1>
  <%= @user.name %>
</h1>
<span>
  <%= pluralize(@user.microposts.count, "tweet") %>
</span>

app/views/users/_follow.html.erb
<%= form_for(current_user.relationships.build(followed_id:@user.id), url: relationships_path(:format => :js), html: { id: "post-form"}) do |f| %>
   <div><%= f.hidden_field :followed_id %></div>
   <%= f.submit "Follow", class: "btn btn-large btn-primary" %>
<% end %>

app/views/users/_follow_form.html.erb
<% unless current_user?(@user) %>
  <div id="follow_form">
  <% if current_user.following?(@user) %>
    <%= render 'unfollow' %>
 <%  else %>
    <%= render 'follow' %>
  <% end %>
  </div>
<% end %>

app/views/users/_unfollow.html.erb
<%- rel= current_user.relationships.find_by_followed_id(@user) %>
<%= form_for(rel, url: relationship_path(rel,:format => :js), html: {method: :delete, id: "delete-form"}) do |f| %>
<% f.submit "Unfollow", class: "btn btn-large" %>
<% end %>

app/views/users/_user.html.erb
<li><%= link_to user.name, user %></li>

app/views/users/index.html.erb
<%= provide(:title, 'All users') %>
<h1>All users</h1>
<%= will_paginate %>
<ul class="users">
  <%= render @users%>
</ul>    
<%=  will_paginate %>

app/views/users/new.html.erb
<% provide(:title, 'Enter User Name') %>
  <h1>Enter User Name</h1>
  <div class="row">
  <div class="span6 offset3">
    <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages', object: f.object %>
      <%= f.label :name %>
      <%= f.text_field  :name %>
      <%= f.submit "Go", class: "btn btn-large btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name)%>
<div class ="row">
  <aside class ="span4">
    <section>
      <%= render 'shared/user_info' %>
    </section>
    <section>
      <%=  render 'shared/stats' %>
    </section>
    <section>
      <%= render 'shared/micropost_form' if current_user?(@user) %>
    </section>
    </aside>
   <div class= "span8">
     <%= render 'users/follow_form' %>
     <% if @feed_items.any? %>
     <h3>Total Feeds (<%= @feed_items.count %>)</h3>
     <ol class ="microposts">
       <%= render @feed_items %>
     </ol>
     <%= will_paginate @feed_items, :remote => true %>
     <% end %>
   </div>
</div>

app/views/users/show_follow.html.erb
<%= provide(:title, @title) %>
<div class ="row">
  <aside class ="span4">
    <section>
      <h1><%= @user.name %></h1>
      <span><b>Tweets:</b> <%= @user.microposts.count %></span>
    </section>
     <%= render 'shared/stats' %>
    </section>
  </aside>
  <div class="span8">
    <h3><%= pluralize(@users.count, @title) %></h3>
    <% if @users.any? %>
      <ul class="users">
        <%= render @users %>
      </ul>
      <%= will_paginate %>
    <% end %>
  </div>
</div>